version: '3'

services:
  main:
    image: yum_recup:latest
    container_name: yum_recup
    hostname: yum-recup
    build:
      dockerfile: ./Dockerfile.yum.yml
      context: .
    volumes:
      - type: bind
        source: ./scripts
        target: /code